/// <reference path="../worker-configuration.d.ts" />
// `Env` (DB, KV, ASSETS bindings) is generated by `pnpm types` from wrangler.jsonc.

declare global {
	namespace App {
		interface Platform {
<<<<<<< HEAD
			env: Env
			ctx: ExecutionContext
			caches: CacheStorage
			cf?: IncomingRequestCfProperties
		}
		interface Locals {
			lang: string
=======
			env: Env;
			ctx: ExecutionContext;
			caches: CacheStorage;
			cf?: IncomingRequestCfProperties;
>>>>>>> 7ddb244 (feat: initialize SvelteKit project with Cloudflare adapter and database setup)
		}
	}
}

<<<<<<< HEAD
export {}
=======
export {};
>>>>>>> 7ddb244 (feat: initialize SvelteKit project with Cloudflare adapter and database setup)
