/// <reference path="../worker-configuration.d.ts" />
import type { Services } from '$lib/server/container'
import type { Lang } from '$lib/i18n/config'
import type { SmtpConfig } from '$lib/server/auth/infrastructure/smtp-email'
import type { R2Config } from '$lib/server/media/infrastructure/r2-storage'

type AuthSession = NonNullable<Awaited<ReturnType<Services['auth']['api']['getSession']>>>
// `Env` (DB, KV, ASSETS bindings) is generated by `pnpm types` from wrangler.jsonc.

declare global {
	namespace App {
		interface Platform {
			env: Env & SmtpConfig & R2Config
			ctx: ExecutionContext
			caches: CacheStorage
			cf?: IncomingRequestCfProperties
		}
		interface Locals {
			lang: Lang
			theme: 'system' | 'light' | 'dark'
			user: AuthSession['user'] | null
			session: AuthSession['session'] | null
			services?: Services
		}
	}
}

export {}
