/// <reference path="../worker-configuration.d.ts" />
import type { Services } from '$lib/server/container'
import type { Preferences } from '$lib/server/preferences/domain/preferences'
import type { Lang } from '$lib/i18n/config'
import type { MailConfig } from '$lib/server/auth/infrastructure/mailtrap-email'
import type { R2Config } from '$lib/server/media/infrastructure/r2-storage'
import type { AuthSecrets } from '$lib/server/auth'

type AuthSession = NonNullable<Awaited<ReturnType<Services['auth']['api']['getSession']>>>
// `Env` (DB, KV, ASSETS bindings) is generated by `pnpm types` from wrangler.jsonc.

declare global {
	namespace App {
		interface Error {
			message: string
			code?: string
		}
		interface Platform {
			env: Env & MailConfig & R2Config & AuthSecrets
			ctx: ExecutionContext
			caches: CacheStorage
			cf?: IncomingRequestCfProperties
		}
		interface Locals {
			lang: Lang
			theme: 'system' | 'light' | 'dark'
			user: AuthSession['user'] | null
			session: AuthSession['session'] | null
			preferences: Preferences | null
			services?: Services
		}
	}
}

export {}
